/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#e1e0ff",
        "on-tertiary": "#502400",
        "tertiary-fixed-dim": "#ffb786",
        "on-primary-container": "#ffffff",
        "on-secondary": "#282964",
        "secondary-container": "#3f407c",
        "on-background": "#e4e1ed",
        "inverse-primary": "#4849dc",
        "surface-container-high": "#292932",
        "error-container": "#93000a",
        "primary-container": "#6163f5",
        background: "#13131b",
        "primary-fixed-dim": "#c1c1ff",
        "on-surface-variant": "#c7c4d7",
        "on-primary": "#1200a9",
        "on-secondary-container": "#aeaff3",
        "on-error-container": "#ffdad6",
        surface: "#13131b",
        "surface-dim": "#13131b",
        "surface-container-low": "#1b1b23",
        "on-primary-fixed-variant": "#2d2ac4",
        error: "#ffb4ab",
        "surface-container-highest": "#34343d",
        tertiary: "#ffb786",
        primary: "#c1c1ff",
        "inverse-on-surface": "#302f39",
        outline: "#908fa1",
        "surface-tint": "#c1c1ff",
        "tertiary-container": "#b95c00",
        "secondary-fixed-dim": "#c1c1ff",
        "on-surface": "#e4e1ed",
        "on-error": "#690005",
        "on-primary-fixed": "#07006c",
        "surface-variant": "#34343d",
        "on-tertiary-fixed": "#311300",
        "secondary-fixed": "#e1e0ff",
        "outline-variant": "#464555",
        secondary: "#c1c1ff",
        "surface-bright": "#393842",
        "on-secondary-fixed": "#12124f",
        "tertiary-fixed": "#ffdcc6",
        "surface-container": "#1f1f28",
        "inverse-surface": "#e4e1ed",
        "surface-container-lowest": "#0d0d16",
        "on-tertiary-fixed-variant": "#723600",
        "on-tertiary-container": "#fffeff",
        "on-secondary-fixed-variant": "#3f407c",
        "background-light": "#f6f6f8",
        "background-dark": "#0a0a0f",
        "brand-gradient-start": "#6366f1",
        "brand-gradient-end": "#8b5cf6"
      },
      fontFamily: {
        display: ["Spline Sans", "sans-serif"],
        headline: ["Spline Sans", "sans-serif"],
        body: ["Spline Sans", "sans-serif"],
        label: ["Spline Sans", "sans-serif"]
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px"
      }
    }
  },
  plugins: [require("@tailwindcss/forms")]
};
